### ISSUE TITLE
Agregar Navegacion entre paginas

### ISSUE THREAD

**Issue by LuisAlejandro12** [ekiim/fakemoney#109]
# Descripción de la funcionalidad
No todas las paginas tienen navegación
 - Describa la funcionalidad que desea añadir al proyecto.
Agregar navegación en las paginas faltantes
 - Describa una propuesta de estrategia para implementarla.
 Agregar por medio de comandos las rutas a otras paginas
 - Describa el beneficio de esta funcionalidad.
 Mejorar la interacción en cuanto al proyecto y cambios 
 - Describa si es que la funcionalidad propuesta rompe con alguna funcionalidad previamente implementada.
 No, solo se agregara código.

**Comment by Maricruz-GML** [comment]
Te ayudo con la navegacion

**Comment by LuisAlejandro12** [comment]
Gracias @Maricruz-GML

**Comment by carlosenrique1402** [comment]
@LuisAlejandro12 ¿A qué archivos en específicos buscas agregar la navegación?

**Comment by Edwinjuarez31** [comment]
@LuisAlejandro12 también me gustaría ayudar y buscar los archivos que necesites paras la navegación

**Comment by LuisAlejandro12** [comment]
@carlosenrique1402 estoy trabajando en la pagina de user.html y @Maricruz-GML me esta ayudando en ubicar los archivos, me si podrían apoyarme en que otras paginas donde se requieran navegacion, estamos trabajando en esta pagina
![image](https://user-images.githubusercontent.com/78774673/112922905-2690a180-90c2-11eb-8d63-fc2ea2a3a769.png)

**Comment by Yadelina** [comment]
@LuisAlejandro12  en cuanto al direccionamiento de las paginas realice el siguiente cambio, estando en el index te mande directo al inicio de sesión / registro  al presionar el botón de registrar, solo espero respuesta del pull request.

![image](https://user-images.githubusercontent.com/78772161/113244753-7dd17600-926a-11eb-956e-228026a82f93.png)
