### ISSUE TITLE
Realice un cambio en la documentación de Ubuntu pero no ha visto reflejada

### ISSUE THREAD

**Issue by marcorodriguez45** [ekiim/fakemoney#110]
# Descripción

Realice un cambio en la documentación de Ubuntu y no se reflejo no se si por que realice un  paso mal
![Captura](https://user-images.githubusercontent.com/78774507/112923201-b3d3f600-90c2-11eb-9397-8daa30adb9dd.PNG)

**Comment by Maytemartrey** [comment]
Si hiciste todos los paso para guardarlo?

**Comment by Maytemartrey** [comment]
Para poder guardar el documento en git son estos paso
1. Ya que se haya editado y guardado pondrás el comando Git push para guardar los cambios
2. Con Git commit revisas si es que tienes uno pendiente te sale un mensaje en color rojo
3. Para enviar los cambios es con Git add por ejemplo (Git add Manual-de-usuario-md)
4. Revisas si es que se guardo te debe salir en color verde
5. Como ultimo realizas el pull request con la descripción corta y guardas
6. Revisas en tu plataforma de git que te salga el pull y terminas de editar ya más específicamente


Espero te sirva (:
