### ISSUE TITLE
Herramientas

### ISSUE THREAD

**Issue by BigMoy** [ekiim/fakemoney#26]
@ekiim  Que herramientas necesitamos 
Python, Docker ...
Podría decirme el orden  y cuales son?

**Comment by LuisAlejandro12** [comment]
?Buenas noches @ekiim, Solo necesitamos instalar 3 herramientas? Docker, Git y Python?

**Comment by ekiim** [comment]
@BigMoy En la pagina de la [wiki](https://github.com/ekiim/fakemoney/wiki) dice...

Primero instala python3.8 o superior.
Después instala git. 

Si no pueden instalar Docker, aun así podrán realizar desarrollo, pero no podrán probar los ambientes de Docker.

Esto no los limitará debido a que las ejecuciones que requieran Docker se pueden hacer desde el servidor, o las puedo realizar yo.

**Comment by LuisAlejandro12** [comment]
Gracias @ekiim
