### ISSUE TITLE
Problemas al instalar pipenv

### ISSUE THREAD

**Issue by Jovanny929** [ekiim/fakemoney#27]
Buenas @ekiim , ya verifique que tengo pip, pero cuando quiero installr pipenv por medio de pip en una terminal PowerShell de windows, no me deja instalarlo

**Comment by ekiim** [comment]
Inténtalo desde una consola normal de Windows el `cmd`. 
 - `<WINDOWS> + R` abre un diálogo de `Run` 
 - Escribir `cmd` en la caja de texto y presionar enter.
 - Esto abre una ventana de la terminal de windows.
 - Correr el comando `pip install pipenv` en dicha ventana.

**Comment by Jovanny929** [comment]
Buenos dias @ekiim ya pude resolver mi problema

**Comment by Brayan9652** [comment]
Yo tuve un problema similar, para resolverlo:
- reinstale phyton https://www.python.org/downloads/release/python-391/
- Simplemente palomee el recuadro (Parte inferior izquierda) que muestra python y luego instale
 una vez instalado clickeas en el unico recuadro y das permisos
- Y por ultimo abres PowerShell y escribes   python -m pip install pipenv
