### ISSUE TITLE
Definir métodos de autenticación de usuarios.

### ISSUE THREAD

**Issue by ekiim** [ekiim/fakemoney#29]
Antes de hablar de la autenticación de usuarios, hay que definir cuales son nuestros usuarios.

Un usuario será, una conexión HTTP, que se realice con el servidor, todas las peticiones deberán ser negadas si el usuario no esta autenticado.

Para autenticar a un usuario, el usuario deberá emitir la solicitud HTTP, con un token del tipo `JWT`, generado por nuestro servidor.

Este token debe contener los siguientes campos en sus afirmaciones (Claims).
```
{
"user_id": "userid",
"accounts": ["Acount1", "Acount2"],
"iat": 0000,
"exp": 0001,
}
```

El token deberá ser rechazado si:
 - Falta alguno de los campos, o los tipos de los campos son incorrectos.
 - El token es inválido (firma inválida).
 - El token expiro.
 - El token es nulo. 

El token deberá ser incluido en la cabecera de la petición `Authorization`, como `Authorization: Bearer {TOKEN}`.

La obtención de un token, será exclusivamente por medio de las rutas en el `api` programado, al momento de procesar una solicitud de inicio de sesión, o de regeneración de token.

**Comment by Santiix28** [comment]
Que tal, me gustaría llevar a cabo esta autentificación, pero no se si primero deba estar funcionando el generador para la obtención de los token, de ser así me gustaría también ayuda con el generador.

**Comment by ekiim** [comment]
Mira el manejo de usuarios como entidad almacenable se realiza en modulo fakemoney y la autenticacion de usuarios se realizara por medio de `jwt` hay que ver el issue #38.

**Comment by Maytemartrey** [comment]
Este se habló durante la clase, en este si no estaba segura si se había concluido
