### ISSUE TITLE
Problema para correr el comando pipenv run start

### ISSUE THREAD

**Issue by Yadelina** [ekiim/fakemoney#33]
al tratar de correr el comando me  aparece lo siguiente
![pipenv](https://user-images.githubusercontent.com/78772161/108277071-acb5e180-712d-11eb-842c-da8338c51528.JPG)

**Comment by ekiim** [comment]
En la terminal escribiste `pipenv start`, eso no es un subcomando valido de `pipenv`, hay que correr `pipenv run start`.

**Comment by Yadelina** [comment]
Gracias, error de sintaxis
