### ISSUE TITLE
Definición de las hojas de estilo a implementar.

### ISSUE THREAD

**Issue by ekiim** [ekiim/fakemoney#37]

**Comment by Maricruz-GML** [comment]
Que caracteristicas deben tener las hojas de estilo?

**Comment by ekiim** [comment]
La hoja de estilos ya existe, se está usando `w3.css` está en el archivo `www/css/w3.css` y adicionalmente existe una extensión para poner estilos especiales de nuestra aplicación llamada `w3-ext.css`, en el mismo directorio.

También observa que hay una hoja de estilo para el tema. 


La documentación de la hoja de estilos esta [aquí](https://www.w3schools.com/w3css/default.asp)

**Comment by Maytemartrey** [comment]
Se habló durante clase
