### ISSUE TITLE
Escritura de un módulo de javascript puro, para realizar transacciones contra el `api`

### ISSUE THREAD

**Issue by ekiim** [ekiim/fakemoney#38]

**Comment by Jovanny929** [comment]
Transacciones general moneterias correcto? Cual seria la estructuracion inicial del codigo para este modulo? De antemano gracias @ekiim

**Comment by ekiim** [comment]
Este es el archivo `www/fakemoney.js`. 

Por lo pronto hay una estructura muy básica de que datos se manejan ahí, hay que implementar llamadas al servidor utilizando `fetch` en javascript, pero primero hay que tener el servidor listo.

**Comment by Jovanny929** [comment]
Me encuentro analizando el archivo e informacion sobre fetch (https://www.w3schools.com/js/js_api_fetch.asp) sin embargo me gustaria orientacion, un poco mas sobre como implementar estas "llamadas al servidor". Utilizaremos el comando "pipenv run start" o "pipenv run www"?

**Comment by Maytemartrey** [comment]
Esto se realizó durante la clase, recuerdo
