### ISSUE TITLE
Diseño de las vistas de Login

### ISSUE THREAD

**Issue by ekiim** [ekiim/fakemoney#39]

**Comment by RichieGaribo** [comment]
donde encuentro la pagina de estilos ccs ? para poder agregar algunos al html

**Comment by ekiim** [comment]
Estamos utilizando una librería que se llama `w3.css`, la documentación está en la siguiente [página](https://www.w3schools.com/w3css).

Para ver templates que utilizan esta librería uno puedo ver la sección de [templates](https://www.w3schools.com/w3css/w3css_templates.asp) en la misma página.

Y si quieres ejemplos puedes ver este [link](https://www.w3schools.com/w3css/w3css_examples.asp)
