### ISSUE TITLE
Diseño de la vista de estado de cuenta

### ISSUE THREAD

**Issue by ekiim** [ekiim/fakemoney#40]

**Comment by rosendo14rs** [comment]
Me interesa entrar a este issue @ekiim.

**Comment by ekiim** [comment]
Ok, abre un archivo idéntico al de `www/users.html`, y 
 - [ ] crea un componente para desplegar datos generales de la cuenta (`www/componentes/account_summary.html`)

**Comment by rosendo14rs** [comment]
listo, me encuentro en eso.

**Comment by ekiim** [comment]
Abre un Pull Request por favor con tu cambio.

**Comment by rosendo14rs** [comment]
esta en Pull Request ahora mismo @ekiim.

**Comment by ekiim** [comment]
Ok, ahora en el archivo de componente que hiciste, hay que incluir código html como el del resto de los componentes para visualizar los datos.

No te preocupes por desplegar datos reales, por lo pronto que la vista quede bonita

**Comment by rosendo14rs** [comment]
tengo una duda.
![image](https://user-images.githubusercontent.com/78774389/110175808-349b1d00-7db7-11eb-99f0-d8713eb82226.png)
esa es la tabla de user, bueno la duda es en donde coloco los datos para visualizarlos asi
![Uploading image.png…]()

**Comment by rosendo14rs** [comment]
tengo una duda al momento de ingresar los datos para poder visualizarlos asi, en donde me colocaria dentro del codigo
![image](https://user-images.githubusercontent.com/78774389/110176320-f2bea680-7db7-11eb-98d5-f3477703f2c1.png)

**Comment by rosendo14rs** [comment]
se que hace referencia a esta tabla html, pero no se donde se ingresan los datos,
![image](https://user-images.githubusercontent.com/78774389/110176424-1bdf3700-7db8-11eb-8f05-db37cc6dfe6e.png)

**Comment by rosendo14rs** [comment]
![image](https://user-images.githubusercontent.com/78774389/110176653-809a9180-7db8-11eb-923c-7a66dc2e226f.png)
me gustaría desplegar algo así, bueno con menos datos.

**Comment by ekiim** [comment]
> se que hace referencia a esta tabla html, pero no se donde se ingresan los datos,
> ![image](https://user-images.githubusercontent.com/78774389/110176424-1bdf3700-7db8-11eb-8f05-db37cc6dfe6e.png)

En el archivo `www/js/fakemoney.js` están los datos de prueba, puedes modificar los ahí para tenerlos accesibles en las tablas.

**Comment by ekiim** [comment]
> ![image](https://user-images.githubusercontent.com/78774389/110176653-809a9180-7db8-11eb-923c-7a66dc2e226f.png)
> me gustaría desplegar algo así, bueno con menos datos.

OK, solo considera que la tabla para transacciones será genérica, así que para este issue hay que hacer la parte de los datos generales y también hacer referencia a la tabla de transacciones.

**Comment by rosendo14rs** [comment]
Perfecto, ya estaba haciendo todo en tablas pero para mejor vista los jalo desde ahí entonces. @ekiim 
![image](https://user-images.githubusercontent.com/78774389/110187383-088a9680-7dcd-11eb-9c75-b8c61a5ad6e1.png)

**Comment by ekiim** [comment]
En la tabla de transacciones, quita la columna de ID, y quita él engrane y solo deja el ojito.
Quita una de las dos tablas de arriba (en nosotros manejamos menos información, además creo que ese es un estado de cuenta de un crédito)
En la tabla del estado de cuenta pon:
 - Saldo Total
 - Egresos del periodo
 - Ingresos del periodo
 - Cantidad de transacciones
 - Fecha de la consulta
 - Periodo de la consulta

**Comment by rosendo14rs** [comment]
estoy teniendo otro problema ya no me deja realizar cambios @ekiim

**Comment by rosendo14rs** [comment]
![image](https://user-images.githubusercontent.com/78774389/110190430-27425a80-7dd8-11eb-8e49-f80d92e37b47.png)
me arroja eso en bash

**Comment by ekiim** [comment]
ese es el log de acceso del servidor de python para la pagina web.

Tienes ahi un 404, porque estas intentando accesar a una imagen que no existe, algun elemento de imagen en la pagina tiene como `src` el valor `{{picture}}`, y por eso causa esos 404. 

No deberia haber problema con eso.

**Comment by rosendo14rs** [comment]
@ekiim metí los cambios como los tengo, pero no me dejo modificar, seguiré intentando y cualquier error subo captura.

**Comment by ekiim** [comment]
@rosendo14rs como va esto?

**Comment by rosendo14rs** [comment]
![image](https://user-images.githubusercontent.com/78774389/113242902-d3a41f00-9266-11eb-8c35-712d576dc4fe.png)
esto es lo que me aparece al guardar cambios pero no me los refleja solo me muestra eso... @ekiim

**Comment by ekiim** [comment]
@rosendo14rs Esto esta en tu rama principal?

**Comment by rosendo14rs** [comment]
@ekiim si, estoy aplicando el remote para el branch

**Comment by rosendo14rs** [comment]
![image](https://user-images.githubusercontent.com/78774389/113245838-9d699e00-926c-11eb-9ed8-13c5f308424e.png)
me dice que necesito resolver eso primero para poder continuar
