### ISSUE TITLE
Como puedo hacer pruebas locales del sitio

### ISSUE THREAD

**Issue by MauricioPrieto26** [ekiim/fakemoney#54]
como puedo ver las modificiones que  realizo en el  archivo index del sitio?
ejemplo: si modificio el color de un boton en el codigo y verlo en tiempo real si en realidad se hizo el cambio ya en la pagina principal que cual quiero usuario ve

**Comment by ekiim** [comment]
Hay que correr el servidor del front end, por medio del comando `pipenv run www`.
Para mas informacion checa la [wiki](/ekiim/fakemoney/wiki)

**Comment by MauricioPrieto26** [comment]
ya tengo instalado pip pero cuando quiero poner este comando me sale este error 
![pipenv error](https://user-images.githubusercontent.com/78811909/109113352-fc2d7c00-76f0-11eb-9173-49088a5e3b41.JPG)

**Comment by MauricioPrieto26** [comment]
Quedo resuelto revolviendo instalando pipenv
