### ISSUE TITLE
Cambiar campo de Username a Correo electronico 

### ISSUE THREAD

**Issue by LuisAlejandro12** [ekiim/fakemoney#56]
# Descripción de la funcionalidad

Debemos cambiar el campo de la pagina de login para ello debemos: 
- Acceder al archivo que se encuentra en www/login.html 
- Ubicar en el código los campos User name y Correo electrónico 
- Modificar los campos 

Como beneficio de este cambio es tener una gran facilidad de interacción para los usuarios.
Este cambio no afecta en su funcionamiento.

**Comment by ekiim** [comment]
Esto depende de #36

**Comment by carlosenrique1402** [comment]
@LuisAlejandro12  Me encargo de esta modificación del campo "username" a "correo electrónico" de www/login.html

**Comment by carlosenrique1402** [comment]
Que tal, observe que el archivo www/login.html fue modificado su estructura, entonces ¿damos por terminado la parte de modificación de este Issue o hay algo más por hacer?

**Comment by ekiim** [comment]
Supongo que si, solo ayúdame a revisar si ya no falta ninguno de los campos que mencionamos en el flujo... 

Otra cosa, hay que abrir un issue, para diseñar un campo de _input_ en html, para teléfonos, más bonito... 

@carlosenrique1402 puedes abrir el issue?

**Comment by carlosenrique1402** [comment]
@ekiim En un momento lo abro, solo una duda: ¿el input debe estar en el archivo www/login.html o en algún otro? para especificarlo a la hora de redactar el Issue.
