### ISSUE TITLE
Falta campo "fecha de nacimiento" en pagina signup

### ISSUE THREAD

**Issue by Maricruz-GML** [ekiim/fakemoney#57]
# Agregar campo "fecha de nacimiento" en pagina Signup

 - Describa la funcionalidad que desea añadir al proyecto.
   Agregar el campo de fecha de nacimiento en la pagina de Signup.
 
 - Describa una propuesta de estrategia para implementarla.
 Agregar dentro de la ruta fakemoney/www/signup.html  el campo de fecha de nacimiento.
 
 - Describa el beneficio de esta funcionalidad.
 Se requiere capturar todos los datos del usuario.
 
 - Describa si es que la funcionalidad propuesta rompe con alguna funcionalidad previamente implementada.

**Comment by ekiim** [comment]
Ok, Ententido...

En el documento `www/signup.html`, entre los tags para Apellido y Correo Electrónico, hay que agregar un input del tipo fecha.

**Comment by Brayan9652** [comment]
Yo puedo corregirlo.
