### ISSUE TITLE
Tengo un error al momento de correr pipenv

### ISSUE THREAD

**Issue by marcorodriguez45** [ekiim/fakemoney#58]
![Captura](https://user-images.githubusercontent.com/78774507/109114032-f8e6c000-76f1-11eb-8f15-48aab498d2ed.PNG)
[#]([url](url)) tuve un error en la momento de correr pipev
![error pipenv](https://user-images.githubusercontent.com/78774507/109111237-6ba16c80-76ed-11eb-8c06-608c35f32eff.PNG)

 - Describa el tipo de problema que presenta.
 En el termina git al momento de correr pipenv me apareció un error
 - Describa el tipo de soluciones que ha intentado.
 - Liste sus versiones de 
  Ubuntu 20.4
  pyton 3.8
 - De ser posible incluya una captura de pantalla con el problema.
 - De ser posible incluya un `paste` de el `output` mensaje de error. (Como bloque de código)
 -attributeError: 'list' object has no attribye 'read'
 

Etiquete a las personas que considera puedan ayudar con dicho problema.

**Comment by ekiim** [comment]
Por favor llena los datos completos del issue.

**Comment by ekiim** [comment]
¿Puedes mostrarme el comando que estás corriendo?

**Comment by marcorodriguez45** [comment]
![Captura](https://user-images.githubusercontent.com/78774507/109114207-29c6f500-76f2-11eb-941f-f9fdf25f6e66.PNG)

**Comment by Maricruz-GML** [comment]
Sigues teniendo problemas?

**Comment by ekiim** [comment]
@marcorodriguez45 actualiza tu branch, estamos utilizados python 3.9

**Comment by Maytemartrey** [comment]
Mi compañero soluciono su problema
