### ISSUE TITLE
Problemas con la instalacion de pipenv

### ISSUE THREAD

**Issue by LuisAlejandro12** [ekiim/fakemoney#60]
# Descripción del problema
![image](https://user-images.githubusercontent.com/78774673/109113392-0ea7b580-76f1-11eb-897e-670f597abcbf.png)

 - Describa el tipo de problema que presenta.
 No puedo instalar pipenv, me marca error y estos mensajes.
 - Describa el tipo de soluciones que ha intentado.
 - Liste sus versiones de 
    - Sistema Operativo : Windows 10
    - `python --version` : 3.9.1
    - `pipenv --version`
    - `git --version` 
 - De ser posible incluya una captura de pantalla con el problema.

Etiquete a las personas que considera puedan ayudar con dicho problema.

**Comment by ekiim** [comment]
Eso no parece un problema, ahí no dice que exista un error, de hecho ese resultado es porque ya tienes instalado `pipenv`.

¿Puedes correr `pipenv --version` y mostrarme el output?

**Comment by LuisAlejandro12** [comment]
Me aparece esto @ekiim 
![image](https://user-images.githubusercontent.com/78774673/109113931-d785d400-76f1-11eb-84c0-f29b9e989ca7.png)

**Comment by MauricioPrieto26** [comment]
Igual tengo el mismo problema pongo ese comando y me sale lo mismo 

![image](https://user-images.githubusercontent.com/78811909/109113986-e79db380-76f1-11eb-882d-5b3a9977c259.png)

**Comment by rosendo14rs** [comment]
igualmente @ekiim me aparece el mismo error de @MauricioPrieto26

**Comment by ekiim** [comment]
Porfavor corran el siguiente comando en la termina. 

```
echo "$PATH"
```
Y por favor peguen el output como texto. 

Recuerden que para poner bloques de código, pueden usar el ```.

**Comment by RichieGaribo** [comment]
![Captura](https://user-images.githubusercontent.com/79493827/109115650-3ba99780-76f4-11eb-8257-7362f39fb67f.PNG)

esto significa que si lo tengo instalado y que esa es mi version verdad,? solo por duda

**Comment by MauricioPrieto26** [comment]
Esto me sale al poner el comando

$ echo "$PATH"
/c/Users/maiqu/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/maiqu/bin:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/cassandra-3.11.8/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/PuTTY:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Python27:/cmd:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Users/maiqu/AppData/Local/Programs/Python/Python39/Scripts:/c/Users/maiqu/AppData/Local/Programs/Python/Python39:/c/Users/maiqu/AppData/Local/Microsoft/WindowsApps:/c/Users/maiqu/.dotnet/tools:/c/Users/maiqu/AppData/Local/GitHubDesktop/bin:/usr/bin/vendor_perl:/usr/bin/core_perl

**Comment by ekiim** [comment]
@RichieGaribo Asi es.

**Comment by LuisAlejandro12** [comment]
![image](https://user-images.githubusercontent.com/78774673/109116077-d1452700-76f4-11eb-819d-6fd7819ce00e.png)
me sale esto @ekiim

**Comment by RichieGaribo** [comment]
> @RichieGaribo Asi es.

okay profe gracias

**Comment by rosendo14rs** [comment]
![image](https://user-images.githubusercontent.com/78774389/109116109-de621600-76f4-11eb-8e68-a33208b5dda6.png)
@ekiim

**Comment by ekiim** [comment]
@rosendo14rs @LuisAlejandro12 Estan atrasados con sus branches, lo que pueden hacer es jalar mis cambios `git pull profe main`. y después volver a correr lo de `pipenv` a ver que pasa... también... si pueden modificar sus variables de ambiente para quitar a python `2.7` y `3.8` del `PATH` porfavor...

**Comment by ekiim** [comment]
@LuisAlejandro12 presiona `<Windows> + R` y en el dialgo que abre ejecuta `sysdm.cpl`.

**Comment by LuisAlejandro12** [comment]
Muy bien, ya le di pull profe main y me sigue mandando el mensaje, ando viendo como cambiar las variables de ambiente 
![image](https://user-images.githubusercontent.com/78774673/109117736-3dc12580-76f7-11eb-9d84-55d3bfe0a133.png)

**Comment by rosendo14rs** [comment]
![image](https://user-images.githubusercontent.com/78774389/109118365-11f26f80-76f8-11eb-8677-4782ab2574e1.png)
listo con las variables...

**Comment by ekiim** [comment]
Ok @rosendo14rs ahora intenta ejecutar en la terminal de `git` `python -m pipenv install -d`.

**Comment by rosendo14rs** [comment]
@LuisAlejandro12 en windows buscamos variables y seleccionamos donde dice editar variables
![image](https://user-images.githubusercontent.com/78774389/109118732-8b8a5d80-76f8-11eb-9e06-3bf33a58186e.png)
ahi es donde se cambia 
![image](https://user-images.githubusercontent.com/78774389/109118798-a52ba500-76f8-11eb-9603-885a3da47578.png)

**Comment by LuisAlejandro12** [comment]
Gracias @rosendo14rs, realizare el seguimiento que me acabas de brindar

**Comment by MauricioPrieto26** [comment]
lo solucione con los siguientes pasos 

1. Primero actualize mi carpeta con el comando git pull profe main
2. el segundo comando que agrege fue python -m pip install pipenv 
3. y al final agrege este comando para correr el index python -m pipenv run www

**Comment by LuisAlejandro12** [comment]
Gracias @ekiim, @rosendo14rs y @MauricioPrieto26 , me sirvió el procedimiento que me dieron.
Lo solucione con los siguientes pasos: 
- Verifique que no tuviera ninguna versión instalada de Python 
- Intente con los comando Python -m pip install pipenv 
- Me dirigí a las aplicaciones de Windows mire que tenia la versión 2.7 de Python y la elimine
-  Cerré terminal de git y volví abrir una 
- Con el comando pip install pipenv 
-  Se descargo pipenv y funciono correctamente
