### ISSUE TITLE
Problemas de overflow en la pagina de Signup

### ISSUE THREAD

**Issue by ekiim** [ekiim/fakemoney#62]
# Problemas de overflow en la pagina de Signup
Tenemos un problema con el overlow

 - Este es un problema de estilos
 - Se encuentra en el documento [`www/signup.html`](https://fakemoney.ekiim.xyz/signup.html)
 - Sugiero, separar la forma en dos partes, que la sección izquierda, tenga los datos básicos de la persona,  y la sección derecha contenta los datos básicos de autenticación.

![Screenshot from 2021-02-24 23-11-39](https://user-images.githubusercontent.com/6476691/109116667-c50d9980-76f5-11eb-9b70-b18b471c11a7.png)

**Comment by ekiim** [comment]
@Brayan9652 Observa esto.

**Comment by Brayan9652** [comment]
Tratare de solucionarlo

**Comment by ekiim** [comment]
@Brayan9652 , creo que esto ya no es un problema, pero por favor ayúdame a verificar esto.

Por cierto, cerré el PR, ya que perdió relevancia, debido al cambio de esquema
