### ISSUE TITLE
Editar el archivo readme.

### ISSUE THREAD

**Issue by ekiim** [ekiim/fakemoney#67]
Hay que editar el archivo `README.md` para que contenga un resumen acerca del proyecto, 

 - El resumen debe contener al menos instrucciones básicas de instalación, algunos links significativos a la wiki.
 - Descripción general del propósito del proyecto.
 - Descripción básica del deprimente.

**Comment by rosendo14rs** [comment]
Me interesa contribuir en el issue @ekiim me podría decir como empezar.

**Comment by ekiim** [comment]
@rosendo14rs por favor consulta las siguientes ligas

 - [Make a README](https://www.makeareadme.com/)
 - [A beginners Guide to writting a readme](https://meakaakka.medium.com/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3)

**Comment by rosendo14rs** [comment]
Listo, estaré trabajando en eso @ekiim.

**Comment by ekiim** [comment]
ok.

**Comment by rosendo14rs** [comment]
Listo, estaré subiéndolo @ekiim.

**Comment by ekiim** [comment]
@rosendo14rs
Revisa #75, y hay que realizar los cambios que mencione.
