### ISSUE TITLE
Problemas con Inicio: Clonacion de repositorio y acceso a proyecto. 

### ISSUE THREAD

**Issue by MiguelOs125** [ekiim/fakemoney#68]
Que tal!

  Desconosco procedimiento para realizacion de clonacion de repositorio, asi mismo que pasos son los que debo seguir para conectarme a proyecto desde mis Bash de git, de igual manera desconosco que procedimiento para realizar movimientos de programacion dentro del proyecto, estoy interesado en Front End en HTML.

@ekiim  @marcorex45  @Yadelina  @OliverImrox  

Saludos.

**Comment by ekiim** [comment]
Hay que crear un fork en la página de github, entra a la página principal del proyecto, 
[ekiim/fakemoney](https://github.com/ekiim/fakemoney), hay que dar clic en el botón de _fork_ a mano derecha en la parte superior, después se te abrirá una copia en tu perfil, donde tendrás una versión tuya del proyecto.
Después de eso, clonas el proyecto y sigues la página de la wiki [Trabajar con un Fork](https://github.com/ekiim/fakemoney/wiki/Trabajar-con-un-Fork)

**Comment by MiguelOs125** [comment]
Gracias a @ekiim 

![Captura](https://user-images.githubusercontent.com/78774447/109592151-a7f51400-7ac3-11eb-8dc8-f63b66d1dca8.JPG)

**Comment by ekiim** [comment]
antes que cierres el issue envíame el output de `git remote -v`

**Comment by MiguelOs125** [comment]
![Captura](https://user-images.githubusercontent.com/78774447/109592359-facecb80-7ac3-11eb-9592-44bf6c1b7bd2.JPG)

Saludos! Logrado el cometido!

**Comment by ekiim** [comment]
Ya estas listo para trabajar.

Si tienes problemas para correr `pipenv` abre otro issue.
