### ISSUE TITLE
Procedimiento para la clonación del proyecto 

### ISSUE THREAD

**Issue by LuisAlejandro12** [ekiim/fakemoney#69]
# Descripción
Debemos crear un documento con los pasos para clonar el proyecto
 - Argumente la razón para el cambio el error que encontró.
 - No hay un documento donde se describa el procedimiento para clonar el proyecto
 - Describa el cambio que se propone (no incluya el cambio solo describa lo)
 - Publicar los pasos para la clonación del proyecto

**Comment by ekiim** [comment]
Hay que realizar estos cambios en el documento de Trabajar con un Fork.

**Comment by ekiim** [comment]
Las imágenes necesarias almacénenlas en un directorio llamado `docs/assets`

**Comment by ekiim** [comment]
@LuisAlejandro12 @Brayan9652

¿Cómo va esto?

**Comment by LuisAlejandro12** [comment]
Bien @ekiim, @Brayan9652 se encargo de subir el procedimiento escrito, yo subire imagenes, ando en eso

**Comment by ekiim** [comment]
@LuisAlejandro12

¿Esto quedará listo antes de la clase?

**Comment by LuisAlejandro12** [comment]
@ekiim acabo de subir mis imagenes al directorio, de echo acabo de crear el pull request, faltan que @Brayan9652 anexe el procedimiento en el documento, pero si queda antes de clase

**Comment by Brayan9652** [comment]
Ya he hecho el pull request para que sea aceptado

**Comment by ekiim** [comment]
@Brayan9652 Ya lo acepté.

**Comment by Maytemartrey** [comment]
Ya no más comentarios, lo último fue que ya estaba hecho
