### ISSUE TITLE
No puedo actualizar mi repositorio

### ISSUE THREAD

**Issue by MauricioPrieto26** [ekiim/fakemoney#71]
# Descripción del problema
Al momento de agregar el comando `git pull profe main
`  me sale este error y en mi brach  me salen summit que no se actualiza
![image](https://user-images.githubusercontent.com/78811909/109601854-7f294a80-7ad4-11eb-8c34-055b1d878c44.png)

![image](https://user-images.githubusercontent.com/78811909/109601730-3c677280-7ad4-11eb-9bce-1653006249e1.png)

Me pueden ayudar  que comando ingresar para agrego mi `git status` ya que no me deja avanzar de aqui

![image](https://user-images.githubusercontent.com/78811909/109602396-e2b37800-7ad4-11eb-9dff-a4412936f4bf.png)

@Yadelina @ekiim @LuisAlejandro12 @marcorex45 @

**Comment by Jovanny929** [comment]
Prueba ahora con el comando git push, y checa si en tu repositorio de GitHub haber si ya se actualizo

**Comment by MauricioPrieto26** [comment]
Puse ese comando y me salio esto 

![image](https://user-images.githubusercontent.com/78811909/109748181-45684a80-7b8d-11eb-9e28-5a9ee36fbf8c.png)

**Comment by ekiim** [comment]
OK, hay que resolver y documentar este procedimiento.

Lo que pasó es que mi repositorio tiene cambios que están en conflicto con los tuyos, lo que vas a hacer es ejecutar `git status` y te mostrará una lista de archivos que tanto tu como yo modificamos, hay que ir a editar esos archivos, y resolver los conflictos, en el archivo se encontrarán los dos bloques de código con las ediciones tuyas y mías, vas a analizarlos, arreglar esos pedazos y remover las acotaciones. Cuando concluyas la edición hay que ejecutar `git add {filename} ` y luego `git rebase - -continue ` y hay que hacer eso hasta que arroje un mensaje de success.

**Comment by MauricioPrieto26** [comment]
Entendido, realizare estos pasos para solucionarlo

**Comment by ekiim** [comment]
A este procedimiento se le llama Git Rebase.

**Comment by MauricioPrieto26** [comment]
Una ves que realizo todas la acciones anteriores me sale este mensaje 

![image](https://user-images.githubusercontent.com/78811909/109845988-8e0e1b00-7c02-11eb-99f1-221f34332055.png)

**Comment by ekiim** [comment]
Hit pusg

**Comment by MauricioPrieto26** [comment]
-Ya me sale al dia mi 

![image](https://user-images.githubusercontent.com/78811909/109870724-506bbb00-7c1f-11eb-977d-e4ecfc868223.png)

-Pero en mi repositorio me sale esto en los commit Esto me puede causar un problema?

![image](https://user-images.githubusercontent.com/78811909/109870952-87da6780-7c1f-11eb-8484-565653a75cd2.png)

**Comment by ekiim** [comment]
@MauricioPrieto26 cuando abras un PR, yo copiare tus cambios, entonces después de que lo acepte y actualices tu branch, estaremos parejos.

**Comment by Brayan9652** [comment]
Yo tengo un problema similiar, no me deja actualizar mi repositorio
![Captura](https://user-images.githubusercontent.com/78774390/109890623-73589800-7c3c-11eb-8fdc-86c83d0c9cfa.PNG)

**Comment by MauricioPrieto26** [comment]
Tienes que entrar a esos archivos y quitar las lineas que estan en conflictos  o modificarlos una ves hecho poner el comando 
`git  add {nombrel del archivo}` para agregarlo a tu repositorio

**Comment by ekiim** [comment]
@MauricioPrieto26 Ya le ayude por llamada a @Brayan9652 , tenia un problema porque el no esta haciendo `rebase` el estaba haciendo `merge`.
