### ISSUE TITLE
Problemas con autenticación

### ISSUE THREAD

**Issue by RoelLopez** [ekiim/fakemoney#73]
Al momento de ingresar el comando git push en la terminal de git bash y iniciar sesión para autorizar git credential manager no me permite aceptar dando click al boton que permite la autorización (Botón verde a un lado del boton de cancelar).
.

**Comment by RoelLopez** [comment]
![fd](https://user-images.githubusercontent.com/78894825/109753335-ed364600-7b96-11eb-81a5-f7c43ef3d10e.PNG)

**Comment by ekiim** [comment]
Puedes mostrarme `git remote -v`

**Comment by RoelLopez** [comment]
![cap](https://user-images.githubusercontent.com/78894825/109760926-70aa6400-7ba4-11eb-97fa-dc24b6cfac9b.PNG)

**Comment by ekiim** [comment]
![image](https://user-images.githubusercontent.com/6476691/109771111-4b702280-7bb1-11eb-9f29-ff920fc88e5d.png)
![image](https://user-images.githubusercontent.com/6476691/109771052-38f5e900-7bb1-11eb-93ca-1271b318816c.png)
![image](https://user-images.githubusercontent.com/6476691/109771090-4612d800-7bb1-11eb-85df-43bcc00c7b8d.png)
![image](https://user-images.githubusercontent.com/6476691/109771133-52973080-7bb1-11eb-9d6c-9f74d31118d7.png)

**Comment by ekiim** [comment]
Acabo de intentar el flujo, yo no tengo problemas...
Te pidió permisos de windows para abrir puertos? 
eso es necesario.

**Comment by ekiim** [comment]
Hay una alternativa, para hacerlo, involucraría cambiar tu remote para que contenga tus credenciales en el mismo url...
puedes ver estas dos ligas...

- [Create personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token)
- [use git credentials](https://git-scm.com/docs/gitcredentials)

**Comment by RoelLopez** [comment]
Listo, ya no tengo problemas, la solución fue crear un token de acceso personal y de esa manera conectarme y permitir
Fue una manera mas sencilla y rápida.

**Comment by ekiim** [comment]
Excelente, daré este Issue por cerrado.
