### ISSUE TITLE
No se puede iniciar pipenv

### ISSUE THREAD

**Issue by MauricioPrieto26** [ekiim/fakemoney#80]
Al momento de correr el comando `pipenv run www` me sale este error

![image](https://user-images.githubusercontent.com/78811909/109920554-4e314d00-7c6f-11eb-8f8b-8206cfc88bfa.png)

**Comment by ekiim** [comment]
corre `python -m pipenv {resto de los argumentos}`

**Comment by MauricioPrieto26** [comment]
Listo corrio perfectamente con ese comando
![image](https://user-images.githubusercontent.com/78811909/109920873-cc8def00-7c6f-11eb-9d1a-e02091c17e4d.png)
