### ISSUE TITLE
cambio de vista de registro 

### ISSUE THREAD

**Issue by RichieGaribo** [ekiim/fakemoney#83]
# Descripción de la funcionalidad

 - Describa la funcionalidad que desea añadir al proyecto.
 mejorar la vista de presentación de registro, nuevo estilo.
![156842457_746478865840413_306062605348207457_n](https://user-images.githubusercontent.com/79493827/109921749-365ac880-7c71-11eb-97c1-9864fe979362.png)

 - Describa una propuesta de estrategia para implementarla.
 propuesta en colores.
 - Describa el beneficio de esta funcionalidad.
 mejor presentación de registro 

 - Describa si es que la funcionalidad propuesta rompe con alguna funcionalidad previamente implementada.

**Comment by carlosenrique1402** [comment]
@RichieGaribo ¿La idea  sería cambiar totalmente la estética o mantener la misma mejorándola con ciertos cambios?

**Comment by marcorodriguez45** [comment]
me gustaría apoyar en esta parte solo coméntenme cual es la idea

**Comment by carlosenrique1402** [comment]
Sigo en espera sobre los comentarios, ya qué también quiero apoyar en esta parte.

**Comment by MiguelOs125** [comment]
@RichieGaribo Buenas! 
Te podria ayudar con algunas funcionalidades o animaciones para darle un poco mas de visibilidad al login y hacerlo un poco mas atrayante a los usuarios.

**Comment by Edwinjuarez31** [comment]
@MiguelOs125 , te puedo ayudar en la visibilidad en el login

**Comment by Edwinjuarez31** [comment]
@carlosenrique1402 en esta pagina , me di la tarea de investigar sobre algunos diseños en freepik para llegar a ser mas llamativos y también con un aspecto formal :
https://www.freepik.es/vector-gratis/pagina-inicio-sesion-ondas-abstractas_5481485.htm#page=1&query=login&position=1

Además, de tambien encontrar algunos logins estaticos para darnos una idea en esta pagina: 
https://www.templatemonster.com/blog/es/100-formularios-html5-css3-gratis-de-registro-ininio-de-sesion/

Lo mejor de este ultimo link es que son de libre uso

**Comment by Maytemartrey** [comment]
Creo recordar que Garibo comentó acerca de este issue y usted le dijo que lo comentara por aquí que ya estaba hecho
