### ISSUE TITLE
Crear un boton de login en el index

### ISSUE THREAD

**Issue by Santiix28** [ekiim/fakemoney#85]
Crear un botón que lleve a la pagina de login para poder iniciar sesión y que este en la pantalla principal.

**Comment by RichieGaribo** [comment]
yo trabajare en el

**Comment by Edwinjuarez31** [comment]
Disculpa @Santiix28 , pero al parecer estuve revisando el proyecto y llegue a encontrar que por parte de @MauricioPrieto26 ya ha creado y hecho el botón para el index antes de tiempo y presiento que esta demás este issue

**Comment by Edwinjuarez31** [comment]
disculpa @Santiix28 , pero checando durante estos dias el proyecto, me di cuenta que por parte de @MauricioPrieto26 , llego a crear el boton de login que estara en el index , asi que creo que esta de mas este issue
