### ISSUE TITLE
ayuda para correr el www

### ISSUE THREAD

**Issue by marcorodriguez45** [ekiim/fakemoney#89]
![www error](https://user-images.githubusercontent.com/78774507/110285254-d1b4ac00-7f97-11eb-887c-559044d62ee9.PNG)
# Descripción del problema
cuando intento correr el www me sale un error persistente
 - Describa el tipo de problema que presenta.
 - Describa el tipo de soluciones que ha intentado.
 - Describa como es que ese problema lo limita para continuar trabajando.

Etiquete a las personas que considera puedan ayudar con dicho problema.

**Comment by MauricioPrieto26** [comment]
Verificia que version de python esta utilizando, por que no esta encontrando ninguno

**Comment by LuisAlejandro12** [comment]
@marcorodriguez45 ya checaste 
- Versión de python 9.1 o superior
- Que hallas instalado pip 
Verifica que lo tengas instalado ambos

**Comment by Brayan9652** [comment]
De aqui puedes descargar la versión que necesitas https://www.python.org/downloads/release/python-391/
Y aquí hay información de como instalar python en Ubuntu https://ubunlog.com/python-3-9-como-instalar-en-ubuntu-20-04/
