### ISSUE TITLE
Problema con realizar de Pull Requests

### ISSUE THREAD

**Issue by MiguelOs125** [ekiim/fakemoney#90]
Que tal!!! 

  Porfavor pido apoyo para realizar un pull request para visualizacion de integrantes de proyecto y admicion de cambios. 
git pull profe main
git pull
git push
git add nombre_del_archivo
git status

  Realize unos cambios interesantes a nivel de codigo HTML, y me gustaria pasar estos cambios a admicion general!!
  
  
![imagen](https://user-images.githubusercontent.com/78774447/110409483-345f8380-803c-11eb-9427-bef9d7f951f0.png)

Me encuentro en esta parte pero en la plataforma GIT, tengo este problema: 
![imagen](https://user-images.githubusercontent.com/78774447/110409535-4b9e7100-803c-11eb-9e78-eeb371954051.png)

No he realizado cambio alguno despues de esto.

**Comment by carlosenrique1402** [comment]
@MiguelOs125 Una vez que agregas el documento, ejemplo: "git add nombre_del_archivo" 
Puedes checar que este en verde como se muestra en tu captura con "git status", una vez hecho eso usa "git commit" para agregar un título o detalle sobre el cambio que realizaste. Finalizas con el comando "git push".

**Comment by Yadelina** [comment]
Después de que haces el git push te puedes ir directo a https://github.com/ekiim/fakemoney/pulls  y ahi tambien puedes generar el pull request un poquito mas a detalle.

**Comment by marcorodriguez45** [comment]
para que pongas que hiciste en el cambio

**Comment by MiguelOs125** [comment]
@carlosenrique1402 
Ya realize el cambio y realize el Git push de manera correcta y me marca todo de manera correcta. Pero gracias queda grabado el procedimiento.

**Comment by MiguelOs125** [comment]
@Yadelina Mira, si checas arriba el pull request me inpide realizarlo, algun apoyo con esta situacion?

**Comment by MiguelOs125** [comment]
@marcorodriguez45  Oye realize algunas pruebas, pero si tienes posibilidad de realizar un ejemplo o algun tutorial?

**Comment by carlosenrique1402** [comment]
@MiguelOs125 Si ya realizaste el push, el cambio se vera reflejado en tu repositorio para que desde esa parte puedas generar el pull request. En la captura no se aprecia el link, así que no sabría si te encuentras en tu repositorio.

**Comment by MiguelOs125** [comment]
@carlosenrique1402 paso captura de pagina completa, estoy realizando el pull request desde Main principal, 
![imagen](https://user-images.githubusercontent.com/78774447/110411832-109e3c80-8040-11eb-97ac-517cc27dbdc7.png)

No entiendo de donde debo de visualizar en mis repositorios.
![imagen](https://user-images.githubusercontent.com/78774447/110411872-2449a300-8040-11eb-936a-22615a6583ea.png)

**Comment by Maytemartrey** [comment]
@MiguelOs125 El pull request que haces aparece en tu perfil, no el del profe

**Comment by MiguelOs125** [comment]
@Yadelina @carlosenrique1402  @marcorodriguez45  
Gracias por su apoyo, @Yadelina  me faltaba realizar el compare forks para que se me habilitara la opcion. 

Saludos!

**Comment by Yadelina** [comment]
@MiguelOs125  creo que en la segunda imagen del "compare"  era al revés Opps error de dedo primero va el repositorio original y lo comparas con el tuyo jeje
