### ISSUE TITLE
Problemas con Ambiente de desarrollo. (primera ejecucion)

### ISSUE THREAD

**Issue by RoelLopez** [ekiim/fakemoney#91]
Problemas para realizar el primer despliegue del proyecto

**Comment by carlosenrique1402** [comment]
@RoelLopez Para ejecutar el ambiente de desarrollo debes tener instalado pipenv, te muestro un siguiente enlace: https://github.com/ekiim/fakemoney/wiki/Como-installar-Pipenv. Ya que instales el pipenv, checa como usar el ambiente que sería la última parte: https://github.com/ekiim/fakemoney/wiki.

**Comment by MauricioPrieto26** [comment]
Puedes poner capturas del error para saber en que paso vas y determinar la solución.

**Comment by OliverImrox** [comment]
@RoelLopez pudiste solucionar tu problema compañero?

**Comment by ekiim** [comment]
@RoelLopez Soluciono su problema?
