### ISSUE TITLE
Implementar metadatos para Open Graph

### ISSUE THREAD

**Issue by ekiim** [ekiim/fakemoney#94]

**Comment by ekiim** [comment]
Ok, espero mas informacion.

**Comment by MauricioPrieto26** [comment]
en esta pagina  `https://ogp.me/`  muestra ejemplos de como poner las linea de codigos y mas funciones que se le puede poner 
seria bueno meter todo el codigo en un archivo y desde el index jalarlo

**Comment by Maytemartrey** [comment]
Hay un issue con el mismo nombre el cual ya está cerrado, es el número 99
