### ISSUE TITLE
Permiso denegado al clonar repositorio

### ISSUE THREAD

**Issue by BigMoy** [ekiim/fakemoney#96]
# Descripción del problema
Al momento de escribir este comando
$ git clone git@github.com:ekiim/fakemoney.git
Cloning into 'fakemoney'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

 - Describa el tipo de problema que presenta.
 - Describa el tipo de soluciones que ha intentado.
 E intentado desinstalar git y instalar de nuevo 

 - Liste sus versiones de 
    - Sistema Operativo
    - windows 10
    - `python --version`
    - 3.8
    - `pipenv --version`
    - 20.11.15
    - `git --version`
 - De ser posible incluya una captura de pantalla con el problema.

 - De ser posible incluya un `paste` de el `output` mensaje de error. (Como bloque de código)
Cloning into 'fakemoney'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Etiquete a las personas que considera puedan ayudar con dicho problema.
@ekiim

**Comment by BigMoy** [comment]
![cp2](https://user-images.githubusercontent.com/78774394/110693632-828b9880-819c-11eb-915e-8822861eff57.PNG)

**Comment by BigMoy** [comment]
estaba Todo bien solo que me surgio este problema
![p1](https://user-images.githubusercontent.com/78774394/110693732-9931ef80-819c-11eb-84f4-5688bf8ff792.PNG)

**Comment by ekiim** [comment]
Eso es porque estás intentando clonar con SSH, si no tienes configurado el SSH no podrás hacerlo. Clona por HTTPS.

**Comment by BigMoy** [comment]
También lo intente llevo desde las 9 intentando
use este otro método y me sale este error}
![cpp](https://user-images.githubusercontent.com/78774394/110694259-3b51d780-819d-11eb-9c90-78a7212746ff.PNG)
@ekiim

**Comment by ekiim** [comment]
corre `git clone https://github.com/BigMoy/fakemoney.git`

**Comment by BigMoy** [comment]
completo
